# Generated by Django 3.2.9 on 2021-11-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=255, unique=True)),
                ('cuidad', models.CharField(max_length=255, unique=True)),
                ('direccion', models.CharField(max_length=255, unique=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento de la reserva')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'ubucaciones',
            },
        ),
    ]
