# Generated by Django 3.2.9 on 2021-11-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='descricao',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='anuncio',
            old_name='criado_em',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='anuncio',
            old_name='alterado_em',
            new_name='midificado',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='perfil/', verbose_name='Imagen de perfil'),
        ),
    ]
