# Generated by Django 3.2.9 on 2021-11-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_auto_20211119_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='imagen/', verbose_name='Imagenes'),
        ),
    ]
